### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by 1375AMG10** [Matrix07ksa/Brute_Force#13]
root@kali:~/Brute_Force# python Brute_Force.py 
pip3 install proxylist                                                                                                                                     
pip3 install mechanize                                                                                                                                     
pip3 install mechanize 
Traceback (most recent call last):
  File "Brute_Force.py", line 72, in <module>
    brows = Browser()
NameError: name 'Browser' is not defined
root@kali:~/Brute_Force# 

???????

**Comment by sergeysova** [comment]
+

**Comment by Aspiringpentester** [comment]
I am also having this problem.
